### PR TITLE
Add breakfast menu

### PR DESCRIPTION
**Pull request by jindasy**
Add breakfast menu. Is it OK to merge?

### CODE REVIEW

**Comment by Siripa-Maneein** [comment]
It seems that you do not add the hyperlink at the top, yet.

**Comment by kulisarawiangin** [comment]
very good

**Comment by jindasy** [comment]
Is it OK to merge?

**Comment by Siripa-Maneein** [comment]
approve.

**Comment by Tanabodee-Yambangyang** [comment]
Approve Jaa.

**Comment by PloyyNK** [comment]
approve

**Comment by kulisarawiangin** [comment]
approve

**Pull request closed without merging**
