### PR TITLE
lunch menu - Add menu table, hyperlink, add id

### PR DESCRIPTION
**Pull request by Siripa-Maneein**
I've added a table menu, a hyperlink, as well as about us. Anything else?

### CODE REVIEW

**Comment by kulisarawiangin** [comment]
Everything looks perfect ka.

**Comment by PloyyNK** [comment]
You should delete TODO

**Comment by Siripa-Maneein** [comment]
I've deleted to do. Anything else?

**Comment by Tanabodee-Yambangyang** [comment]
The items are not in alphabetical order.

**Comment by Siripa-Maneein** [comment]
Am I ready to merge, yet?

**Comment by Tanabodee-Yambangyang** [comment]
Wow, approve!!!

**Comment by Siripa-Maneein** [comment]
Is it ok to merge?

**Comment by jindasy** [comment]
approve

**Comment by PloyyNK** [comment]
approve

**Comment by kulisarawiangin** [comment]
approved

**Comment by Tanabodee-Yambangyang** [comment]
Yeah Approve!!

**Pull request merged**
