### PR TITLE
change beverages menu

### PR DESCRIPTION
**Pull request by kulisarawiangin**
Add beverages menu

### CODE REVIEW

**Comment by Siripa-Maneein** [comment]
Everything looks good.

**Comment by PloyyNK** [comment]
Item should be in alphabetical order

**Comment by Siripa-Maneein** [comment]
approve.

**Comment by jindasy** [comment]
approve

**Comment by Tanabodee-Yambangyang** [comment]
Approve!

**Comment by PloyyNK** [comment]
approve

**Pull request merged**
