### PR TITLE
Dinner menu

### PR DESCRIPTION
**Pull request by PloyyNK**
Already add dinner menu. Ready to merge?

### CODE REVIEW

**Comment by Siripa-Maneein** [comment]
Please, delete TODO.

**Comment by jindasy** [comment]
Please add your surname in About Us.

**Comment by kulisarawiangin** [comment]
very good ka

**Comment by jindasy** [comment]
Approve.

**Comment by Siripa-Maneein** [comment]
approve.

**Comment by Tanabodee-Yambangyang** [comment]
Approve Krubb.

**Pull request merged**
